### PR TITLE
Fix regression in TransactionTableModel

### LINKED ISSUE #7: Crash on exit
On master (dbd7a91fdf3ff801fe5e4107e8346d0d6d11a899):

```
$ lldb ./src/qt/bitcoin-qt -- -testnet
(lldb) target create "./src/qt/bitcoin-qt"
Current executable set to './src/qt/bitcoin-qt' (x86_64).
(lldb) settings set -- target.run-args  "-testnet"
(lldb) run
Process 5006 launched: './src/qt/bitcoin-qt' (x86_64)
Process 5006 stopped
* thread #1, name = 'bitcoin-qt', stop reason = signal SIGSEGV: invalid address (fault address: 0x38)
    frame #0: 0x00007ffff72e1fa0 libpthread.so.0`__GI___pthread_mutex_lock
libpthread.so.0`__GI___pthread_mutex_lock:
->  0x7ffff72e1fa0 <+0>:  movl   0x10(%rdi), %eax
    0x7ffff72e1fa3 <+3>:  movl   %eax, %edx
    0x7ffff72e1fa5 <+5>:  andl   $0x17f, %edx              ; imm = 0x17F 
    0x7ffff72e1fab <+11>: nop    
(lldb) bt
error: bitcoin-qt :: Class 'ClientModel' has a base class 'QObject' which does not have a complete definition.
error: bitcoin-qt :: Try compiling the source file with -fstandalone-debug.
* thread #1, name = 'bitcoin-qt', stop reason = signal SIGSEGV: invalid address (fault address: 0x38)
  * frame #0: 0x00007ffff72e1fa0 libpthread.so.0`__GI___pthread_mutex_lock
    frame #1: 0x00005555555ea443 bitcoin-qt`ClientModel::getBestBlockHash() [inlined] __gthread_mutex_lock(__mutex=0x0000000000000028) at gthr-default.h:748
    frame #2: 0x00005555555ea43b bitcoin-qt`ClientModel::getBestBlockHash() [inlined] std::mutex::lock(this=0x0000000000000028) at std_mutex.h:103
    frame #3: 0x00005555555ea42d bitcoin-qt`ClientModel::getBestBlockHash() [inlined] std::unique_lock<std::mutex>::lock(this=<unavailable>) at std_mutex.h:267
    frame #4: 0x00005555555ea42d bitcoin-qt`ClientModel::getBestBlockHash() [inlined] UniqueLock<AnnotatedMixin<std::mutex>, std::unique_lock<std::mutex> >::Enter(this=<unavailable>, pszFile=<unavailable>, nLine=119) at sync.h:139
    frame #5: 0x00005555555ea42d bitcoin-qt`ClientModel::getBestBlockHash() [inlined] UniqueLock<AnnotatedMixin<std::mutex>, std::unique_lock<std::mutex> >::UniqueLock(this=<unavailable>, mutexIn=0x0000000000000028, pszFile=<unavailable>, nLine=119, fTry=false) at sync.h:160
    frame #6: 0x00005555555ea42d bitcoin-qt`ClientModel::getBestBlockHash() [inlined] ClientModel::getBestBlockHash(this=<unavailable>)::$_2::operator()() const at clientmodel.cpp:119
    frame #7: 0x00005555555ea42d bitcoin-qt`ClientModel::getBestBlockHash(this=0x0000000000000000) at clientmodel.cpp:119
    frame #8: 0x00005555556a23f6 bitcoin-qt`TransactionTableModel::index(this=0x0000555556472cf0, row=11, column=4, parent=<unavailable>) const at transactiontablemodel.cpp:667
    frame #9: 0x00007ffff5a9c5e9 libQt5Core.so.5`___lldb_unnamed_symbol1919$$libQt5Core.so.5 + 249
    frame #10: 0x00007ffff5a9cb56 libQt5Core.so.5`QSortFilterProxyModel::flags(QModelIndex const&) const + 166
    frame #11: 0x00007ffff6adf3c5 libQt5Widgets.so.5`QListView::moveCursor(QAbstractItemView::CursorAction, QFlags<Qt::KeyboardModifier>) + 437
    frame #12: 0x00007ffff6aad083 libQt5Widgets.so.5`QAbstractItemView::focusInEvent(QFocusEvent*) + 259
    frame #13: 0x00007ffff68987ff libQt5Widgets.so.5`QWidget::event(QEvent*) + 2479
    frame #14: 0x00007ffff69394de libQt5Widgets.so.5`QFrame::event(QEvent*) + 30
    frame #15: 0x00007ffff6942623 libQt5Widgets.so.5`QAbstractScrollArea::event(QEvent*) + 899
    frame #16: 0x00007ffff6aac87b libQt5Widgets.so.5`QAbstractItemView::event(QEvent*) + 187
    frame #17: 0x00007ffff685983c libQt5Widgets.so.5`QApplicationPrivate::notify_helper(QObject*, QEvent*) + 156
    frame #18: 0x00007ffff6861104 libQt5Widgets.so.5`QApplication::notify(QObject*, QEvent*) + 676
    frame #19: 0x00007ffff5adb8d8 libQt5Core.so.5`QCoreApplication::notifyInternal2(QObject*, QEvent*) + 280
    frame #20: 0x00007ffff685ecbe libQt5Widgets.so.5`QApplicationPrivate::setFocusWidget(QWidget*, Qt::FocusReason) + 526
    frame #21: 0x00007ffff68927ef libQt5Widgets.so.5`QWidget::setFocus(Qt::FocusReason) + 415
    frame #22: 0x00007ffff685f14b libQt5Widgets.so.5`QApplication::setActiveWindow(QWidget*) + 1067
    frame #23: 0x00007ffff685f243 libQt5Widgets.so.5`QApplicationPrivate::notifyActiveWindowChange(QWindow*) + 51
    frame #24: 0x00007ffff609eee5 libQt5Gui.so.5`QGuiApplicationPrivate::processActivatedEvent(QWindowSystemInterfacePrivate::ActivatedWindowEvent*) + 789
    frame #25: 0x00007ffff609f14d libQt5Gui.so.5`QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) + 557
    frame #26: 0x00007ffff60762eb libQt5Gui.so.5`QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 171
    frame #27: 0x00007fffecd98260 libQt5XcbQpa.so.5`___lldb_unnamed_symbol984$$libQt5XcbQpa.so.5 + 16
    frame #28: 0x00007ffff19d5417 libglib-2.0.so.0`g_main_context_dispatch + 743
    frame #29: 0x00007ffff19d5650 libglib-2.0.so.0`___lldb_unnamed_symbol192$$libglib-2.0.so.0 + 512
    frame #30: 0x00007ffff19d56dc libglib-2.0.so.0`g_main_context_iteration + 44
    frame #31: 0x00007ffff5b3488f libQt5Core.so.5`QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 95
    frame #32: 0x00007ffff5ad990a libQt5Core.so.5`QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 314
    frame #33: 0x00007ffff5ae29b4 libQt5Core.so.5`QCoreApplication::exec() + 148
    frame #34: 0x00005555555d2985 bitcoin-qt`GuiMain(argc=<unavailable>, argv=<unavailable>) at bitcoin.cpp:594
    frame #35: 0x00005555555cea43 bitcoin-qt`main(argc=<unavailable>, argv=<unavailable>) at main.cpp:21
    frame #36: 0x00007ffff3c7db97 libc.so.6`__libc_start_main(main=(bitcoin-qt`main at main.cpp:21), argc=2, argv=0x00007fffffffdcf8, init=<unavailable>, fini=<unavailable>, rtld_fini=<unavailable>, stack_end=0x00007fffffffdce8) at libc-start.c:310
    frame #37: 0x00005555555ce96a bitcoin-qt`_start + 42
```

### PR DESCRIPTION
**Pull request by hebasto**
Since https://github.com/bitcoin/bitcoin/pull/17993 a crash is possible on exit.

Steps to reproduce:
- precondition: the old chain
- start `bitcoin-qt`
- wait until sync
- on main window: Menu -> File -> Quit
- crash

This PR is based on ryanofsky's [suggestion](https://github.com/bitcoin-core/gui/issues/7#issuecomment-646639251).

Fixes #7.

### CODE REVIEW

File: src/qt/transactiontablemodel.cpp [hunk 1]
```diff
@@ -664,7 +664,7 @@ QVariant TransactionTableModel::headerData(int section, Qt::Orientation orientat
 QModelIndex TransactionTableModel::index(int row, int column, const QModelIndex &parent) const
 {
     Q_UNUSED(parent);
-    TransactionRecord* data = priv->index(walletModel->wallet(), walletModel->clientModel().getBestBlockHash(), row);
+    TransactionRecord* data = priv->index(walletModel->wallet(), walletModel->getLastBlockProcessed(), row);
```
Comment (ryanofsky) [inline src/qt/transactiontablemodel.cpp:667]: In commit "qt: Fix regression in TransactionTableModel" (cd3b6d0666fe0e6191596e2aa56980ab60841f2d)

Maybe also add null check on line 195 above:

https://github.com/bitcoin-core/gui/blob/cd3b6d0666fe0e6191596e2aa56980ab60841f2d/src/qt/transactiontablemodel.cpp#L195

```c++
if (!cur_block_hash.IsNull() && rec->statusUpdateNeeded(cur_block_hash) && wallet.tryGetTxStatus(rec->hash, wtx, numBlocks, block_time)) { 
```

To avoid spurious updateStatus calls during shutdown

**Comment by hebasto** [comment]
Updated cd3b6d0666fe0e6191596e2aa56980ab60841f2d -> 9735b0750bc1e510a5ca6764f9d3cdca5cc7f760 ([pr8.01](https://github.com/hebasto/gui/commits/pr8.01) -> [pr8.02](https://github.com/hebasto/gui/commits/pr8.02), [diff](https://github.com/hebasto/gui/compare/pr8.01..pr8.02)):

- added @ryanofsky's [suggestion](https://github.com/bitcoin-core/gui/pull/8#discussion_r442886173)

File: src/qt/transactiontablemodel.cpp (hunk 1 above)
Comment (hebasto) [reply src/qt/transactiontablemodel.cpp:667]: [Updated](https://github.com/bitcoin-core/gui/pull/8#issuecomment-646712144).

**Comment by vasild** [comment]
ACK 9735b075

Maybe both commits should be squashed because the second fixes an issue from the first.

File: src/qt/walletmodel.h [hunk 2]
```diff
@@ -155,6 +155,9 @@ class WalletModel : public QObject
     AddressTableModel* getAddressTableModel() const { return addressTableModel; }
 
     void refresh(bool pk_hash_only = false);
+
+    uint256 getLastBlockProcessed();
```
Comment (promag) [inline src/qt/walletmodel.h:159]: cd3b6d0666fe0e6191596e2aa56980ab60841f2d

Can be const.

File: src/qt/transactiontablemodel.cpp (hunk 1 above)
Comment (promag) [reply src/qt/transactiontablemodel.cpp:667]: 9735b0750bc1e510a5ca6764f9d3cdca5cc7f760

nit, assert block hash is not null in `TransactionRecord::statusUpdateNeeded`.

Comment (hebasto) [reply src/qt/transactiontablemodel.cpp:667]: @promag
> nit, assert block hash is not null in `TransactionRecord::statusUpdateNeeded`.

Does this suggestion implies that `status.needsUpdate` should be the first operand of OR in `TransactionRecord::statusUpdateNeeded()`?

File: src/qt/walletmodel.h (hunk 2 above)
Comment (hebasto) [reply src/qt/walletmodel.h:159]: > Can be const.

Correct.

**Comment by promag** [comment]
I've a slight preference to "fix" before merging, suggestions so far are trivial.

**Comment by hebasto** [comment]
@promag I will happy to fix, just awaiting a response for https://github.com/bitcoin-core/gui/pull/8#discussion_r443245815 :)

File: src/qt/transactiontablemodel.cpp (hunk 1 above)
Comment (promag) [reply src/qt/transactiontablemodel.cpp:667]: No, I don't mean to change that.

File: src/qt/transactionrecord.cpp [hunk 3]
```diff
@@ -234,7 +234,7 @@ void TransactionRecord::updateStatus(const interfaces::WalletTxStatus& wtx, cons
 
 bool TransactionRecord::statusUpdateNeeded(const uint256& block_hash) const
 {
-    return status.m_cur_block_hash != block_hash || status.needsUpdate;
+    return (!block_hash.IsNull() && status.m_cur_block_hash != block_hash) || status.needsUpdate;
```
Comment (promag) [inline src/qt/transactionrecord.cpp:237]: I meant
```cpp
assert(!block_hash.IsNull());
return status.m_cur_block_hash != block_hash || status.needsUpdate;
```

**Comment by hebasto** [comment]
Updated 9735b0750bc1e510a5ca6764f9d3cdca5cc7f760 -> d906aaa117e337fc70575beecc0d6da314f57385 ([pr8.02](https://github.com/hebasto/gui/commits/pr8.02) -> [pr8.04](https://github.com/hebasto/gui/commits/pr8.04), [diff](https://github.com/hebasto/gui/compare/pr8.02..pr8.04)):

- addressed all comments
- squashed

File: src/qt/walletmodel.h (hunk 2 above)
Comment (hebasto) [reply src/qt/walletmodel.h]: [Updated](https://github.com/bitcoin-core/gui/pull/8#issuecomment-647760931).

File: src/qt/transactiontablemodel.cpp (hunk 1 above)
Comment (hebasto) [reply src/qt/transactiontablemodel.cpp:667]: [Updated](https://github.com/bitcoin-core/gui/pull/8#issuecomment-647760931).

File: src/qt/transactionrecord.cpp (hunk 3 above)
Comment (hebasto) [reply src/qt/transactionrecord.cpp]: [Updated](https://github.com/bitcoin-core/gui/pull/8#issuecomment-647760931).

**Comment by hebasto** [comment]
@MarcoFalke Mind looking into this PR?
