### PR TITLE
Fix create unsigned transaction fee bump

### LINKED ISSUE #810: Create unsigned when increasing fee asks for the passphrase
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

Trying to increase the fee on a pending transaction, creating a psbt is asking for the passphrase, though it shouldn't need to unlock the wallet to create a psbt (and didn't require when creating the initial transaction).

### Expected behaviour

Create the psbt without the need for unlocking the wallet

### Steps to reproduce

Locked wallet
Set PSBT actions to enabled in settings
create a transaction with a fee increase replacement option and send it
raise the fee
Choose create PSBT
Get prompt for wallet unlock

### Relevant log output

_No response_

### How did you obtain Bitcoin Core

Package manager

### What version of Bitcoin Core are you using?

26.0.0.0

### Operating system and version

Ubuntu 22.04

### Machine specifications

_No response_

### PR DESCRIPTION
**Pull request by furszy**
Fixes #810.

Not much to explain; we were requiring the wallet to be unlocked for the unsigned transaction creation process.
Fix this by moving the unlock wallet request to the signed transaction creation process.

### CODE REVIEW

**Review by pablomartin4btc — COMMENTED** [review]
Concept ACK

I'll test it soon.

**Review by MarnixCroes — APPROVED** [review]
tack 671b7a32516d62e1e79393ded4b45910bd08010a

`Send` prompts the  passphrase, `Create Unsigned` does not prompt the passphrase

File: src/qt/walletmodel.cpp [hunk 1]
```diff
@@ -549,10 +543,15 @@ bool WalletModel::bumpFee(uint256 hash, uint256& new_hash)
         DataStream ssTx{};
         ssTx << psbtx;
         GUIUtil::setClipboard(EncodeBase64(ssTx.str()).c_str());
-        Q_EMIT message(tr("PSBT copied"), tr("Copied to clipboard", "Fee-bump PSBT saved"), CClientUIInterface::MSG_INFORMATION);
+        Q_EMIT message(tr("PSBT copied"), tr("Fee-bump PSBT copied to clipboard"), CClientUIInterface::MSG_INFORMATION | CClientUIInterface::MODAL);
```
Comment (pablomartin4btc) [inline src/qt/walletmodel.cpp:546]: At least on Ubuntu 22.04, now after the fee-bumping unsigned a modal pop-up is displayed:

image

while before there was a message sent thru the OS system information (?):

image

I see in the code we usually use `CClientUIInterface::MSG_INFORMATION` (`transactionview.cpp`, `walletview.cpp`) and I'd prefer to keep this look & feel but at the same time I think having the modal window popping up it's making the user more aware of what just happened with the intention to accept it.

**Review by pablomartin4btc — APPROVED** [review]
tACK 671b7a32516d62e1e79393ded4b45910bd08010a

Tested and verified this PR fixes #810 and now creation of unsigned tx/ PSBT/ during fee-bumping doesn't ask for passphrase/ requires wallet unlock.

File: src/qt/walletmodel.cpp (hunk 1 above)
Comment (furszy) [reply src/qt/walletmodel.cpp:546]: The change was introduced because the OS system notification wasn't popping up on macOS. Either way is ok for me.

**Review by hebasto — APPROVED** [review]
ACK 671b7a32516d62e1e79393ded4b45910bd08010a, tested on Ubuntu 24.04.

**Comment by fanquake** [comment]
Backported in https://github.com/bitcoin/bitcoin/pull/30092.
