### PR TITLE
refactor: Misc int sign change fixes

### LINKED ISSUE #805: implicit-integer-sign-change wallet/interfaces.cpp:289:57
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

```
wallet/interfaces.cpp:289:57: runtime error: implicit conversion from type 'int' of value -1 (32-bit, signed) to type 'unsigned int' changed the value to 4294967295 (32-bit, unsigned)
    #0 0x55dcca43aaea in wallet::(anonymous namespace)::WalletImpl::createTransaction(std::vector<wallet::CRecipient, std::allocator<wallet::CRecipient>> const&, wallet::CCoinControl const&, bool, int&, long&) src/wallet/interfaces.cpp:289:57
    #1 0x55dcc9439953 in WalletModel::prepareTransaction(WalletModelTransaction&, wallet::CCoinControl const&) src/qt/walletmodel.cpp:211:37
    #2 0x55dcc9624ce5 in SendCoinsDialog::PrepareSendText(QString&, QString&, QString&) src/qt/sendcoinsdialog.cpp:287:28
    #3 0x55dcc960c98b in SendCoinsDialog::sendButtonClicked(bool) src/qt/sendcoinsdialog.cpp:482:10
    #4 0x55dcc9665fdc in auto auto GUIUtil::ExceptionSafeConnect<QPushButton*, void (QAbstractButton::*)(bool), SendCoinsDialog*, void (SendCoinsDialog::*)(bool)>(QPushButton*, void (QAbstractButton::*)(bool), SendCoinsDialog*, void (SendCoinsDialog::*)(bool), Qt::ConnectionType)::'lambda'(auto&&...)::operator()<bool&>(auto&&...) const src/./qt/guiutil.h:400:21
```

### Expected behaviour

no sign change

### Steps to reproduce

* Compile with integer sanitizer
* Create transaction in the gui

### Relevant log output

_No response_

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

master

### Operating system and version

Linux

### Machine specifications

_No response_

### PR DESCRIPTION
**Pull request by maflcko**
This is allowed by the language. However, the `integer` sanitizer complains about it. Thus, fix it, so that the `integer` sanitizer can be used in the future to catch unintended sign changes.

Fixes #805.

### CODE REVIEW

**Comment by hebasto** [comment]
Concept ACK.

**Review by pablomartin4btc — COMMENTED** [review]
tACK 05416422d354b29d59558ce227e076028338b442

I've [reproduced](https://github.com/bitcoin-core/gui/issues/805#issuecomment-2024113934) the 3 errors [described](https://github.com/bitcoin-core/gui/pull/806#issuecomment-2013305029) within this PR.

Tested on Ubuntu 22.04, this PR fixes 2 of the 3 errors.

2nd. commit 321f105d08ddf958881908ea57ad263ffdccd225 doesn't fix [error](https://github.com/bitcoin-core/gui/pull/806#issuecomment-2013305029)  `UndefinedBehaviorSanitizer: implicit-signed-integer-truncation-or-sign-change` on `qt/notificator.cpp` which is only shown when using  `--with-sanitizers=undefined,integer`, using `--with-sanitizers=integer` doesn't produce the error.

File: src/qt/notificator.cpp [hunk 1]
```diff
@@ -112,10 +112,10 @@ FreedesktopImage::FreedesktopImage(const QImage &img):
...
     for(unsigned int ptr = 0; ptr < num_pixels; ++ptr)
     {
-        image[ptr*BYTES_PER_PIXEL+0] = data[ptr] >> 16; // R
-        image[ptr*BYTES_PER_PIXEL+1] = data[ptr] >> 8;  // G
-        image[ptr*BYTES_PER_PIXEL+2] = data[ptr];       // B
-        image[ptr*BYTES_PER_PIXEL+3] = data[ptr] >> 24; // A
+        image[ptr * BYTES_PER_PIXEL + 0] = char(data[ptr] >> 16); // R
+        image[ptr * BYTES_PER_PIXEL + 1] = char(data[ptr] >> 8);  // G
+        image[ptr * BYTES_PER_PIXEL + 2] = char(data[ptr]);       // B
+        image[ptr * BYTES_PER_PIXEL + 3] = char(data[ptr] >> 24); // A
```
Comment (pablomartin4btc) [inline src/qt/notificator.cpp:118]: nit: since we are touching this, perhaps we could use `static_cast<char>` instead of the C-style?
```suggestion
        image[ptr * BYTES_PER_PIXEL + 0] = static_cast<char>(data[ptr] >> 16); // R
        image[ptr * BYTES_PER_PIXEL + 1] = static_cast<char>(data[ptr] >> 8);  // G
        image[ptr * BYTES_PER_PIXEL + 2] = static_cast<char>(data[ptr]);       // B
        image[ptr * BYTES_PER_PIXEL + 3] = static_cast<char>(data[ptr] >> 24); // A
```

**Review by pablomartin4btc — COMMENTED** [review]
I've been playing a bit with the code and found out that the problem was a mix of the fix you provided in the 2nd commit, plus the initialisation of `hasAlpha` in the constructor of `FreedesktopImage`. It seems setting it in the `private:` section of the class definition works and the error is not raised 🙄.

```
private:
    int width, height, stride;
    bool hasAlpha{true};

```

**Review by hebasto — APPROVED** [review]
ACK 05416422d354b29d59558ce227e076028338b442, I have reviewed the code and it looks OK.
